[IN-2003] send logs from macminis to datadog
bitrise-io/gen2-infrastructure pull request #2
Opened 2020-10-13 12:20 UTC by lmesz-bitrise

2020-10-13 12:22 UTC, bitrise-tom approved these changes

2020-10-13 15:37 UTC, peterheja-bitrise submitted a review, later dismissed
LGTM (but the CODEOWNERS should've been a separate PR)

2020-10-14 16:07 UTC, peterheja-bitrise commented on templates/logs.conf.yaml.j2
> +      - "environment:{{ ansible_hostname.split('-')[1] }}"
Seems a bit implicit.

2020-10-15 06:50 UTC, lmesz-bitrise commented on templates/logs.conf.yaml.j2
> +      - "environment:{{ ansible_hostname.split('-')[1] }}"
What is your suggestion?

2020-10-15 07:32 UTC, lmesz-bitrise commented on templates/logs.conf.yaml.j2
> +      - "environment:{{ ansible_hostname.split('-')[1] }}"
We talked offline. Using group_vars instead of this.

2020-10-15 11:29 UTC, peterheja-bitrise commented on templates/logs.conf.yaml.j2
> +      - "env:anka"
I think this should be changed.
`env` should be "production" and "staging" and so on, which is currently `production_env`.
I think this could be renamed to `hypervisor_type`, or rather (to let it also be bare metal or something like that) it should be `generation`, but I like the `hypervisor_type` more.

2020-10-15 11:30 UTC, peterheja-bitrise commented on templates/logs.conf.yaml.j2
> +      - "env:anka"
On other metrics the `env` means DEN env the autoscaler/worker is joined to.

2020-10-15 11:52 UTC, lmesz-bitrise commented on templates/logs.conf.yaml.j2
> +      - "env:anka"
Fixed.

2020-10-15 12:20 UTC, bitrise-tom requested changes

2020-10-15 12:20 UTC, bitrise-tom commented on inventory/ATL01-STG001
> +production_env=staging
What's the reason for this variable?
Can we just make this `environment=` ?

2020-10-15 12:21 UTC, MrBlaise approved these changes

2020-10-15 12:21 UTC, lmesz-bitrise commented on inventory/ATL01-STG001
> +production_env=staging
Nothing anymore, I forget to rename it. Fixed it :)

2020-10-15 12:32 UTC, fehersanyi-bitrise commented on templates/logs.conf.yaml.j2
> +    path: "/Library/Logs/Anka/*.log"
if you wildcard here all logs, why do you need the 2 specified files above?

2020-10-15 12:37 UTC, lmesz-bitrise commented on templates/logs.conf.yaml.j2
> +    path: "/Library/Logs/Anka/*.log"
anka log was excluded, but I changed the pattern. Since only vm logs name contains - I added it to the pattern

2020-10-15 12:38 UTC, fehersanyi-bitrise approved these changes

2020-10-15 12:59 UTC, bitrise-tom approved these changes

2020-10-15 12:59 UTC, merged