[IN-2052] codify anka client
bitrise-io/gen2-infrastructure pull request #5
Opened 2020-10-16 12:55 UTC by lmesz-bitrise

2020-10-16 15:04 UTC, peterheja-bitrise requested changes
See comment.

2020-10-16 15:04 UTC, peterheja-bitrise commented on roles/setup_system/tasks/main.yml
> +  register: administrator_sudoers_state
This is unnecessary, if we use ansible's built in copy

2020-10-16 15:04 UTC, peterheja-bitrise commented on roles/setup_datadog/tasks/main.yml
> +    url: https://s3.amazonaws.com/dd-agent/scripts/install_mac_os.sh
Why don't we use https://formulae.brew.sh/cask/datadog-agent ?

2020-10-16 15:06 UTC, lmesz-bitrise commented on roles/setup_datadog/tasks/main.yml
> +    url: https://s3.amazonaws.com/dd-agent/scripts/install_mac_os.sh
Caaaaaaau it didn't come into my mind, fixing :)

2020-10-16 15:09 UTC, lmesz-bitrise commented on roles/install_anka/tasks/main.yml
> +  shell: /usr/local/bin/anka --help
Right, checking license date

2020-10-16 15:23 UTC, lmesz-bitrise commented on roles/setup_system/tasks/main.yml
> +  register: administrator_sudoers_state
Fixed.

2020-10-18 10:57 UTC, bitrise-tom requested changes

2020-10-18 10:57 UTC, bitrise-tom commented on roles/setup_datadog/tasks/main.yml
> +- name: stop
These two launchctl commands should at least match at the start

2020-10-18 10:57 UTC, bitrise-tom commented on roles/setup_system/tasks/main.yml
> +- name: Remove the sleep image file to save disk space
can we use the file module here?

2020-10-18 10:57 UTC, bitrise-tom commented on roles/setup_system/tasks/main.yml
> +- name: Create a zero-byte file instead...
you can use the file module with `state=touch`

2020-10-18 10:57 UTC, bitrise-tom commented on setup_macmini.playbook.yml
> +    - setup_system
Just a comment, but do we really need the prefixes on these roles?

Install_* just needs to be the anka or tools role
setup_* is obvious. 

I find them easier to read and find alphabetically

2020-10-18 15:00 UTC, lmesz-bitrise commented on roles/setup_datadog/tasks/main.yml
> +- name: stop
You are right, fixed

2020-10-18 15:00 UTC, lmesz-bitrise commented on roles/setup_system/tasks/main.yml
> +- name: Remove the sleep image file to save disk space
Sure, sure forget that. Didn't worked at first but figured out ansible executed all the commands on my hostmachine :)

2020-10-18 15:01 UTC, lmesz-bitrise commented on roles/setup_system/tasks/main.yml
> +- name: Create a zero-byte file instead...
Done.

2020-10-18 15:01 UTC, lmesz-bitrise commented on setup_macmini.playbook.yml
> +    - setup_system
I agree, removed the setup and install prefixes from all the roles.

2020-10-19 12:15 UTC, fehersanyi-bitrise submitted a review, later dismissed
this is awesome, but don't we need to activate the anka license after installing? 🧐 and accept the EULA or what

2020-10-20 09:40 UTC, lmesz-bitrise commented
> this is awesome, but don't we need to activate the anka license after installing? 🧐 and accept the EULA or what

Yeah, you are totally right, I accidentally removed the accept license and forget to add EULA accept at all.

2020-10-20 10:52 UTC, bitrise-tom requested changes

2020-10-20 10:52 UTC, bitrise-tom commented on README.md
> +# How to test roles locally
on MacOS

2020-10-20 10:52 UTC, bitrise-tom commented on roles/anka/tasks/main.yml
> +  shell: /usr/local/bin/anka license show | grep -q "status              | valid                   |"
`anka license validate
License is valid!`

This may be a nicer command to run here. I don't know if the exit code is != 0 if the license is invalid. Needs testing on an unlicensed box

2020-10-20 10:52 UTC, bitrise-tom commented on roles/ssh/files/keys/vagrant
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKjMFW6dsnYmD1KrMONuy7l1IpRQyOiM5nNXsd5lnYZkGyvcEP48FTNmR2d9dPukRknzdIiQUXIH8f4IEQ1Q8tdWp+FanF0Ft+hsIxG63DIoIanRcfajtbGjDrF4ZKGKPsPc8voKx31tmSYfJv5twdBHygNTSCRGm
not sure we need this here

2020-10-20 10:52 UTC, bitrise-tom commented on setup_macmini.playbook.yml
> +  remote_user: vagrant
administrator

2020-10-20 10:52 UTC, bitrise-tom commented on setup_macmini.playbook.yml
> +    - ansible_sudo_pass: vagrant
not this

2020-10-20 10:52 UTC, bitrise-tom commented on setup_macmini.playbook.yml
> +    - param_user: vagrant
administrator

2020-10-20 10:52 UTC, bitrise-tom commented on setup_macmini.playbook.yml
> +    - hostname: LAS1-DEV001-gen2-mmg4-003
remove

2020-10-20 11:47 UTC, lmesz-bitrise commented on roles/setup_datadog/tasks/main.yml
> +    url: https://s3.amazonaws.com/dd-agent/scripts/install_mac_os.sh
Officialy supported way of install of datadog on mac is to use the install_mac_os.sh. I changed it back to this cause the brew install installeddatadog as root and it was not reliable

2020-10-20 11:51 UTC, lmesz-bitrise commented on roles/anka/tasks/main.yml
> +  shell: /usr/local/bin/anka license show | grep -q "status              | valid                   |"
I fixed the condition to fail on any non zero exit code. Is it better or you want me to change it to something else? @bitrise-tom

2020-10-20 11:51 UTC, lmesz-bitrise commented on setup_macmini.playbook.yml
> +  remote_user: vagrant
Fixed, thanks

2020-10-20 11:55 UTC, fehersanyi-bitrise approved these changes

2020-10-20 11:55 UTC, bitrise-tom approved these changes

2020-10-20 11:57 UTC, merged